### ISSUE TITLE
Benchmark Direct Solr vs. Blacklight JSON API Queries

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_rails_api#11]
Investigate the performance of querying solr directly vs. querying the blacklight API. We will have four applications that can be addressed in either way. 

- Catalog
- Pulfalight
- DPUL
- maps.princeton.edu

**Comment by sandbergja** [comment]
According to [one benchmark test](https://github.com/pulibrary/allsearch_rails_api/pull/15#issuecomment-1717943930), this application responds 6x faster when communicating with solr directly, rather than via blacklight.
