### ISSUE TITLE
Add Datadog - The Rails Side

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_rails_api#24]
https://www.datadoghq.com/blog/monitoring-rails-with-datadog/#set-up-rails-application-performance-monitoring

**Comment by kevinreiss** [comment]
Currently we are adding datadog to only production applications.

**Comment by sandbergja** [comment]
#59 helps with this, but we need to wait until #30 before we can check the configuration on production

**Comment by sandbergja** [comment]
Confirmed that this configuration works with https://github.com/pulibrary/princeton_ansible/pull/4279 in place.
