### ISSUE TITLE
Add Art Museum Search Service

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/allsearch_rails_api#48]
## Description
Add a service that executes a keyword search of the Art Museum Collection

### Source Service End User URL
https://artmuseum.princeton.edu/search/collections

### Supporting Service Documentation
https://github.com/Princeton-University-Art-Museum/puam-api-docs (we are currently searching "Objects").

### Connectivity
No authentication required to use the api. 

### Acceptance Criteria

- [ ] Returns the results to the equivalent of  a basic keyword query of the service
- [ ] Provides Search results with the same default sort as the native service
  interface 
- [ ] API response should include a count of the total results
- [ ] API response should include a link to source service search results page, so that a user can continue their search there
- [ ] API response should include the first 3 results from the source
  application
- [ ] API Resource should include the following fields
    * Title Field
    * URL
    * Date
    * Creator
    * Object ID

### Implementation Notes
Current discoveryutils output: https://library.princeton.edu/utils/arts/artobjects?query=picasso&sid=library-main
Current implementation: https://github.com/pulibrary/discoveryutils/tree/main/classes/Arts

**Comment by kevinreiss** [comment]
I think this one may already be done.

**Comment by christinach** [comment]
resolved by https://github.com/pulibrary/allsearch_rails_api/pull/6
