### ISSUE TITLE
Remove submodule

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/allsearch_rails_api#55]
I tried adding a git submodule for pul_solr.  It didn't work well, so I tried to remove it.

However, it still seems to be in main?

We should [follow these steps](https://gist.github.com/myusuf3/7f645819ded92bda6677) to remove it completely.

**Comment by christinach** [comment]
In this case I run:
`git rm --cached solr`
`git add.`
`git commit -m 'message...'`
