### ISSUE TITLE
Persist rails logs across deploys

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/allsearch_rails_api#67]
Right now, when we deploy, the logs remain in the old deployment directory.  So if you want to see all the logs, you have to travel to 5 different directories.  And since we only keep 5 old deployments, any older logs are just deleted.

We should include the logs directory in the "shared" directory (where the bundle and the temp directory are now), so that it doesn't disappear when we deploy.

**Comment by acozine** [comment]
This functionality is controlled by the `linked_dirs:` directive in `config/deploy.rb`. See [pdc_describe](https://github.com/pulibrary/pdc_describe/blob/53144046ca4befa1848c7f08b33fdc7155e4d19c/config/deploy.rb#L6.) for an example.
